Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account.views import *

app_name='account'

urlpatterns=[
    path('register', register, name='register'),
    path('edit', edit_profile, name='edit_profile'),
    path('set_password/', set_password, name='set_password'),
    path('logout_user/', logout_user, name='logout'),
    path('main/account/', login , name='account'),
]

api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('product/',views.listproduct),
    path('category/',views.listcategory),
    path('review/',views.listreview),
    path('product/images/',views.listproductimage),
    path('card/',views.listcard),
    path('cardproduct/',views.listcardproduct),
    path('enterproduct/',views.listenterproduct),
    path('wishlist/',views.listwishlist)
]

main/urls.py
from django.urls import path
from .views import *

app_name='main'

urlpatterns=[
    path('',index, name='index'),
    path('detail/<int:id>',detail, name='detail'),
    path('carts',carts,name='carts'),
    path('cart_detail/<int:id>',cart_detail,name='cart_detail'),
    path('cart_detail_delete/<int:id>',cart_detail_delete,name='cart_detail_delete'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('buy_cart/<int:id>/', buy_cart, name='buy_cart'),
    path('list_wishlist', list_wishlist, name='list_wishlist'),
    path('create_wishlist/', create_wishlist, name='create_wishlist'),
    path('delete_wish/', delete_wish, name='delete_wish'),

]

account/models.py
from django.db import models

# Create your models here.

account/views.py
from django.contrib.auth import authenticate, login as auth_login,logout
from django.shortcuts import render,redirect
from django.db import IntegrityError
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)  
            return redirect('main:index')
        else:
            return render(request, 'login/account.html', {'error_message': 'Invalid email or password'})

    return render(request, 'login/account.html')





def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        password_confirmation = request.POST.get('password_confirmation')
        try:
            if password == password_confirmation:
                user = User.objects.create_user(username=username, password=password)
                return redirect('main:index')
        except IntegrityError:
            return redirect('account:register')
        
    
    return render(request, 'login/register.html')



    





@login_required
def edit_profile(request):
    if request.method == "POST":
        username = request.POST['username']
        first_name = request.POST['first_name']
        email = request.POST['email']
        user = request.user
        user.username = username
        user.first_name = first_name
        user.email = email
        user.save()
    return render(request, 'login/edit.html')


def set_password(request):

    old = request.POST['old']
    new = request.POST['new']
    confirm = request.POST['confirm']
    user = request.user
    if user.check_password(old) and new == confirm:
        user.set_password(new)
        user.save()
    return redirect('account:login/edit_profile')



def logout_user(request):
    user1=request.user
    logout(user1)
    return redirect('login')

account/templates/login/account.html

{% extends 'base.html' %}
{% load static %}
{% block content %}



	<!--account-starts-->
	<div class="account">
		<div class="container">
		<div class="account-top heading">
				<h2>ACCOUNT</h2>
			</div>
			<form method="post">
				{% csrf_token %}
				<div class="account-main">
					<div class="col-md-6 account-left">    
						<h3>Existing User</h3>
						<div class="account-bottom">
							<input placeholder="Email" type="text" name="username">
							<input placeholder="Password" type="password" name="password">
							<div class="address">
								<a class="forgot" href="{% url 'account:register' %}">Forgot Your Password?</a>
								{% if user.is_authenticated %}
								<a class="forgot" href="{% url 'account:edit_profile' %}">Edit Profile</a>
								{% endif %}
								<input type="submit" value="Login">
							</div>
						</div>
					</div>
				</div>
			</form>
			
				<div class="col-md-6 account-right account-left">
					<h3>New User? Create an Account</h3>
					<p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
					<a href="{% url 'account:register' %}">Create an Account</a>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--account-end-->

{% endblock %}

account/templates/login/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Luxury Watches | Home</title>
<link href="{% static 'asosiy/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--jQuery(necessary for Bootstrap's JavaScript plugins)-->
<script src="{% static 'asosiy/js/jquery-1.11.0.min.js' %}"></script>
<!--Custom-Theme-files-->
<!--theme-style-->
<link href="{% static 'asosiy/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--start-menu-->
<script src="{% static 'asosiy/js/simpleCart.min.js' %}"> </script>
<link href="{% static 'asosiy/css/memenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'asosiy/js/memenu.js' %}"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>	
<!--dropdown-->
<script src="{% static 'asosiy/js/jquery.easydropdown.js' %}"></script>			
</head>
<body> 
	<!--top-header-->
	<div class="top-header">
		<div class="container">
			<div class="top-header-index">
				<div class="col-md-6 top-header-left">
					<div class="drop">
						<div class="box">
							<select tabindex="4" class="dropdown drop">
								<option value="" class="label">Dollar :</option>
								<option value="1">Dollar</option>
								<option value="2">Euro</option>
							</select>
						</div>
						<div class="box1">
							<select tabindex="4" class="dropdown">
								<option value="" class="label">English :</option>
								<option value="1">English</option>
								<option value="2">French</option>
								<option value="3">German</option>
							</select>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
				<div class="col-md-6 top-header-left">
					<div class="cart box_1">
						<a href="{% url 'main:cards' %}">
							 <div class="total">
								<span class="simpleCart_total"></span></div>
								<img src="{% static 'asosiy/images/cart-1.png' %}" alt="" />
						</a>
						<p><a href="{% url 'main:cards' %}" class="simpleCart_empty">Empty Cart</a></p>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--top-header-->
		<!--start-logo-->
		<div class="logo">
			<a href="{% url 'main:index'%}"><h1>Luxury Watches</h1></a>
		</div>
		<!--start-logo-->
		<!--bottom-header-->
		<div class="header-bottom">
			<div class="container">
				<div class="header">
					<div class="col-md-9 header-left">
					<div class="top-nav">
						<ul class="memenu skyblue"><li class="active"><a href="{% url 'main:index'%}">Home</a></li>
							
							<li class="grid"><a href="#">Category</a>
								<div class="mepanel">
									<div class="row">
										<div class="col1 me-one">
											{% for i in category %}
											<a href="#"><h4>{{i.name}}</h4></a>
											{% endfor %}
										</div>
									</div>
								</div>
							</li>
							
							<li class="grid"><a href="contact.html">Contact</a>
							</li>
							<li class="grid"><a href="{% url 'account:account' %}">Login</a>
							</li>
						</ul>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="col-md-3 header-right"> 
					<div class="search-bar">
						<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
						<input type="submit" value="">
					</div>
				</div>
				<div class="clearfix"> </div>
				</div>
			</div>
		</div>
		<!--bottom-header-->

		
	<!--start-breadcrumbs-->
	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-index">
				<ol class="breadcrumb">
					<li><a href="{% url 'main:index' %}">Home</a></li>
					<li class="active">Register</li>
				</ol>
			</div>
		</div>
	</div>
	<!--end-breadcrumbs-->
{% block content %}
{% endblock %}


	<!--information-starts-->
	<div class="information">
		<div class="container">
			<div class="infor-top">
				<div class="col-md-3 infor-left">
					<h3>Follow Us</h3>
					<ul>
						<li><a href="#"><span class="fb"></span><h6>Facebook</h6></a></li>
						<li><a href="#"><span class="twit"></span><h6>Twitter</h6></a></li>
						<li><a href="#"><span class="google"></span><h6>Google+</h6></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>Information</h3>
					<ul>
						<li><a href="#"><p>Specials</p></a></li>
						<li><a href="#"><p>New Products</p></a></li>
						<li><a href="#"><p>Our Stores</p></a></li>
						<li><a href="contact.html"><p>Contact Us</p></a></li>
						<li><a href="#"><p>Top Sellers</p></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>My Account</h3>
					<ul>
						{% if user.is_authenticated %}
						<li><a href="{% url 'account:edit' %}"><p>My Account</p></a></li>
						{% else %}
						<li><a href="{% url 'account:account' %}"><p>My Account</p></a></li>
						{% endif %}
						<li><a href="#"><p>My Credit slips</p></a></li>
						<li><a href="#"><p>My Merchandise returns</p></a></li>
						<li><a href="#"><p>My Personal info</p></a></li>
						<li><a href="#"><p>My Addresses</p></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>Store Information</h3>
					<h4>The company name,
						<span>Lorem ipsum dolor,</span>
						Glasglow Dr 40 Fe 72.</h4>
					<h5>+955 123 4567</h5>	
					<p><a href="mailto:example@email.com">contact@example.com</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--information-end-->
    	<!--footer-starts-->
	<div class="footer">
		<div class="container">
			<div class="footer-top">
				<div class="col-md-6 footer-left">
					<form>
						<input type="text" value="Enter Your Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email';}">
						<input type="submit" value="Subscribe">
					</form>
				</div>
				<div class="col-md-6 footer-right">					
					<p>© 2015 Luxury Watches. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--footer-end-->	
</body>
</html>

account/templates/login/edit.html
{% extends 'base.html' %}
{% block content %}


<div class="account">
    <div class="container">
    <div class="account-top heading">
            <h2>ACCOUNT</h2>
        </div>
        <div class="account-main">
            <div class="col-md-6 account-left">
                <h3>Existing User</h3>
                <div class="account-bottom">
                    <form method="post">
                        {% csrf_token %}
                    <label for="">Username</label>
                    <input type="text" tabindex="3" required="" value="{{user.username}}" name="username">
                    <label for="">First Name</label>
                    <input type="text" tabindex="4" value="{{user.first_name}}" name="first_name">
                    <label for="" style="display: block;"> Email </label>
                    <input type="email" tabindex="5" value="{{user.email}}" style=" width: 90%; height: 36px;" name="email">
                    <div class="address">
                        <button type="submit" class="btn btn-primary">O`zgartirish</button>
                    </div>
                </form>
                </div>
            </div>
            <div class="col-md-6 account-left">
                <h3>Existing User</h3>
                <div class="account-bottom">
                    <form action="{% url 'account:set_password' %}" method="post">
                        {% csrf_token %}
                    <label for="">Parol kiritiring</label>
                    <input placeholder="***" type="password" tabindex="3" required="" name="old">
                    <label for="">Yangi Parol kiritiring</label>
                    <input placeholder="***" type="password" tabindex="3" required="" name="new">
                    <label for="">Yangi Parol tasdiqlang</label>
                    <input placeholder="***" type="password" tabindex="4" required="" name="confirm">
                    <div class="address">
                        <button type="submit" class="btn btn-primary">O`zgartirish</button>
                    </div>
                    
                </form>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

{% endblock %}

account/templates/login/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<!--register-starts-->
	<form method="post">
		{% csrf_token %}
		<div class="register">
			<div class="container">
				<div class="register-top heading">
					<h2>REGISTER</h2>
				</div>
				<div class="register-main">
					<div class="col-md-6 account-left">
						<input placeholder="Email address" type="text"  name="username">
					</div>
					<div class="col-md-6 account-left">
						<input placeholder="Password" type="password"  name="password">
						<input placeholder="Retype password" type="password" name="password_confirmation">
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="address submit">
					<input type="submit" value="Submit">
				</div>
			</div>
		</div>
	</form>
	
	<!--register-end-->



	{% endblock %}