Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api/', include('api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account.views import *

app_name='account'

urlpatterns=[
    path('register', register, name='register'),
    path('edit', edit_profile, name='edit_profile'),
    path('set_password/', set_password, name='set_password'),
    path('logout_user/', logout_user, name='logout'),
    path('main/account/', login , name='account'),
]

api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('product/',views.listproduct),
    path('category/',views.listcategory),
    path('review/',views.listreview),
    path('product/images/',views.listproductimage),
    path('card/',views.listcard),
    path('cardproduct/',views.listcardproduct),
    path('enterproduct/',views.listenterproduct),
    path('wishlist/',views.listwishlist)
]

main/urls.py
from django.urls import path
from .views import *

app_name='main'

urlpatterns=[
    path('',index, name='index'),
    path('detail/<int:id>',detail, name='detail'),
    path('carts',carts,name='carts'),
    path('cart_detail/<int:id>',cart_detail,name='cart_detail'),
    path('cart_detail_delete/<int:id>',cart_detail_delete,name='cart_detail_delete'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('buy_cart/<int:id>/', buy_cart, name='buy_cart'),
    path('list_wishlist', list_wishlist, name='list_wishlist'),
    path('create_wishlist/', create_wishlist, name='create_wishlist'),
    path('delete_wish/', delete_wish, name='delete_wish'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from functools import reduce
from django.db.models import Sum

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    quantity = models.IntegerField()
    price = models.DecimalField(decimal_places=2, max_digits=10)
    currency = models.SmallIntegerField(
        choices=(
            (1,'Dollar'), 
            (2, 'So`m')
            )
    ) 
    discount_price = models.DecimalField(
        decimal_places=2, 
        max_digits=10, 
        blank=True, 
        null=True
        )
    baner_image = models.ImageField(upload_to='baner/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)


    @property
    def review(self):
        reviews = ProductReview.objects.filter(product_id=self.id)
        result = reduce(lambda result, x: result +x.mark, reviews, 0)
        try: 
            result = round(result / reviews.count())

        except  ZeroDivisionError:
            result=0
        return result
    
    @property 
    def is_discount(self):
        return self.discount_price > 0
    
    @property 
    def is_active(self):
        return self.quantity > 0
    
    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):

        return self.product.name


class WishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    mark = models.SmallIntegerField()


class Card(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    @property
    def quantity(self):
        return CardProduct.objects.filter(card=self).aggregate(Sum('quantity'))['quantity__sum'] 

    @property
    def total_price(self):
        result = 0
        for i in CardProduct.objects.filter(card_id=self.id):
            result +=(i.product.price)*i.quantity
        return result


class CardProduct(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


    
    @property
    def price(self):
        # print(self.product.is_discount)
        # if self.product.is_discount :
        #     result = self.product.discount_price * self.quantity
        # else:
        result = self.product.price * self.quantity
        return result
    

    
class EnterProduct(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    product_name = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quantity}"
    
    def save(self, *args, **kwargs):
        if self.product:
            self.product_name = self.product.name
            if self.pk:
                enter = EnterProduct.objects.get(pk=self.pk)
                product = enter.product
                product.quantity -= enter.quantity
                product.quantity += self.quantity
                product.save()
            else:
                self.product.quantity += self.quantity
                self.product.save()
        super(EnterProduct, self).save(*args, **kwargs)




    



    


    

main/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .models import Card, CardProduct, Category, Product, ProductImage, ProductReview, WishList


def index(request):
    card = Card.objects.all() 
    cardproduct = CardProduct.objects.all() 
    category = Category.objects.all() 
    product = Product.objects.all() 
    productimage = ProductImage.objects.all() 
    productreview = ProductReview.objects.all()
    
    user_id = request.user.id
    if request.user.is_authenticated:
        # Assuming you have a specific product instance, replace 'specific_product' with the actual product instance
        specific_product = Product.objects.get(pk=1)  # Replace '1' with the actual product ID
        objects = WishList.objects.filter(user=request.user, product=specific_product)
        
        is_saved = None
        if objects:
            is_saved = objects.first().id
        else:
            is_saved = False



    is_saved = None
    # WishList uchun is_saved qiymati olish
    # if request.user.is_authenticated:  # Foydalanuvchining tizimga kirganligini tekshirish
    #     objects = WishList.objects.filter(user=request.user)
    #     if objects.product.id==product.id:
    #         is_saved = objects.first().id
    #     else:
    #         is_saved = False


    context = {
        'card': card,
        'cardproduct': cardproduct,
        'category': category,
        'product': product,
        'productimage': productimage,
        'wishList': WishList.objects.filter(user=request.user),
        'productreview': productreview,
        'user': request.user,
        'is_saved': is_saved,
        'user_id':user_id
    }

    return render(request, 'index.html', context)







def card_product(request):
    card_products = CardProduct.objects.all()
    return render(request, 'index.html', {'card_products': card_products})


def categories(request):
    categories = Category.objects.all()
    return render(request, 'index.html', {'categories': categories})


def products(request):
    products = Product.objects.all()
    return render(request, 'index.html', {'products': products})




#vazifaga



from django.shortcuts import get_object_or_404

def detail(request, id):
    products = Product.objects.all()
    product = get_object_or_404(Product, id=id)

    # Check if the product has a category before accessing its id
    category_id = product.category.id if product.category else None
    
    images = ProductImage.objects.filter(product_id=product.id)
    recomendation = Product.objects.filter(category_id=category_id).exclude(id=product.id)[:3]
    objects = WishList.objects.filter(user=request.user, product=product)
    is_saved = None
    if objects:
        is_saved = objects.first().id
    else:
        is_saved = False

    user_review = ProductReview.objects.filter(user=request.user, product=product).first()
    baho = user_review.mark if user_review else 0
    context = {
        'products': products,
        'product': product,
        'images': images,
        'range': range(baho+1),
        'recomendation': recomendation,
        'is_saved': is_saved
    }

    return render(request, 'single.html', context)









def product_image(request):
    product_images = ProductImage.objects.all()
    return render(request, 'index.html', {'product_images': product_images})


def product_review(request):
    product_reviews = ProductReview.objects.all()
    return render(request, '.html', {'product_reviews': product_reviews})


def wishlist(request):
    wishlists = WishList.objects.all()
    return render(request, '.html', {'wishlists': wishlists})







#carts



def carts(request):
    active=Card.objects.filter(is_active=True,user=request.user)
    in_active=Card.objects.filter(is_active=False,user=request.user)
    context={
        'active':active,
        'in_active':in_active
    }
    return render(request,'cart/carts.html',context)


def cart_detail(request,id):
    cart=Card.objects.get(id=id)
    items=CardProduct.objects.filter(card=cart)

    context={
        'cart':cart,
        'items':items
    }
    return render(request,'cart/cart_detail.html',context)


def cart_detail_delete(request):
    item_id = request.GET['items_id']
    item = CardProduct.objects.get(id=item_id)
    cart_id = item.card.id
    item.delete()
    return redirect('main:cart_detail', cart_id)






def add_to_cart(request, id):
    product = get_object_or_404(Product, id=id)

    user = request.user
    active_card = Card.objects.filter(user=user, is_active=True).first()

    if not active_card:
        active_card = Card.objects.create(user=user)


    existing_product = CardProduct.objects.filter(card=active_card, product=product).first()

    if existing_product:
        existing_product.quantity += 1
        existing_product.save()
    else:
        CardProduct.objects.create(card=active_card, product=product, quantity=1)
    return redirect('main:carts')





def buy_cart(request, id):
    cart=Card.objects.get(id=id , is_active=True)
    cart_products=CardProduct.objects.filter(card=cart)
    for cart_product in cart_products:
        product=cart_product.product
        product.quantity-=cart_product.quantity
        product.save()
    cart.is_active = False
    cart.save()
    return redirect('main:carts')



def create_wishlist(request):
    WishList.objects.create(
        user=request.user,
        product_id=request.GET['product_id']
    )

    return redirect('main:index')


def list_wishlist(request):
    objects=WishList.objects.filter(user=request.user)
    return render(request, 'wish/list.html', {'objects':objects})

from django.shortcuts import get_object_or_404, redirect

def delete_wish(request, id):
    user = request.user
    wish = get_object_or_404(WishList, product_id=id, user=user)
    wish.delete()
    return redirect('main:detail')

















    

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Luxury Watches | Home</title>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--jQuery(necessary for Bootstrap's JavaScript plugins)-->
<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!--Custom-Theme-files-->
<!--theme-style-->
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--start-menu-->
<script src="{% static 'js/simpleCart.min.js' %}"> </script>
<link href="{% static 'css/memenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/memenu.js' %}"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>	
<!--dropdown-->
<script src="{% static 'js/jquery.easydropdown.js' %}"></script>	
<style>
	



.rating-stars {
	display: block;
	width: 50vmin;
	padding: 1.75vmin 10vmin 2vmin 3vmin;
	background: linear-gradient(90deg, #ffffff90 40vmin, #fff0 40vmin 100%);
	border-radius: 5vmin;
	position: relative;
}

	.rating-counter {
		font-size: 5.5vmin;
		font-family: Arial, Helvetica, serif;
		color: #9aacc6;
		width: 10vmin;
		text-align: center;
		background: #0006;
		position: absolute;
		top: 0;
		right: 0;
		height: 100%;
		border-radius: 0 5vmin 5vmin 0;
		line-height: 10vmin;
	}

.rating-counter:before {
	content: "0";
	transition: all 0.25s ease 0s;	
}



input { display: none; }

label {
	width: 5vmin;
	height: 5vmin;
	background: #000b;
	display: inline-flex;
	cursor: pointer;
	margin: 0.5vmin 0.65vmin;
	transition: all 1s ease 0s;	
	clip-path: polygon(50% 0%, 66% 32%, 100% 38%, 78% 64%, 83% 100%, 50% 83%, 17% 100%, 22% 64%, 0 38%, 34% 32%);
}

label[for=rs0] {
	display: none;
}

label:before {
	width: 90%;
	height: 90%;
	content: "";
	background: orange;
	z-index: -1;
	display: block;
	margin-left: 5%;
	margin-top: 5%;
	clip-path: polygon(50% 0%, 66% 32%, 100% 38%, 78% 64%, 83% 100%, 50% 83%, 17% 100%, 22% 64%, 0 38%, 34% 32%);
	background: linear-gradient(90deg, yellow, orange 30% 50%, #184580 50%, 70%, #173a75 100%);
	background-size: 205% 100%;
	background-position: 0 0;
}

label:hover:before {
	transition: all 0.25s ease 0s;		
}

input:checked + label ~ label:before {
	background-position: 100% 0;
	transition: all 0.25s ease 0s;	
}

input:checked + label ~ label:hover:before {
	background-position: 0% 0
}





#rs1:checked ~ .rating-counter:before {
	content: "1";
}

#rs2:checked ~ .rating-counter:before {
	content: "2";
}

#rs3:checked ~ .rating-counter:before {
	content: "3";
}

#rs4:checked ~ .rating-counter:before {
	content: "4";
}

#rs5:checked ~ .rating-counter:before {
	content: "5";
}

label + input:checked ~ .rating-counter:before {
	color: #ffab00 !important;
	transition: all 0.25s ease 0s;
}





label:hover ~ .rating-counter:before {
	color: #9aacc6 !important;
	transition: all 0.5s ease 0s;	
	animation: pulse 1s ease 0s infinite;
}

@keyframes pulse {
	  50% { font-size: 6.25vmin; }
}

label[for=rs1]:hover ~ .rating-counter:before {
	content: "1" !important;
}

label[for=rs2]:hover ~ .rating-counter:before {
	content: "2" !important;
}

label[for=rs3]:hover ~ .rating-counter:before {
	content: "3" !important;
}

label[for=rs4]:hover ~ .rating-counter:before {
	content: "4" !important;
}

label[for=rs5]:hover ~ .rating-counter:before {
	content: "5" !important;
}


input:checked:hover ~ .rating-counter:before {
	animation: none !important;
	color: #ffab00 !important ;
}








/*** INITIAL ANIMATION - Not Necessary ***/
/*** I want to make a loop here ***/

label + input + label:before {
    animation: start 0.5s ease 0s 1;
}

.rating-stars:hover label + input + label:before {
    animation: none;
}

label[for=rs2]:before {
	animation-delay: 0.1s;
}

label[for=rs3]:before {
	animation-delay: 0.2s;
}

label[for=rs4]:before {
	animation-delay: 0.3s;
}

label[for=rs5]:before {
	animation-delay: 0.4s;
}

@keyframes start {
	10%, 90% { background-position: 0% 0; }
}


</style>		
</head>
<body> 
	<!--top-header-->
	<div class="top-header">
		<div class="container">
			<div class="top-header-index">
				<div class="col-md-6 top-header-left">
					<div class="drop">
						<div class="box">
							<select tabindex="4" class="dropdown drop">
								<option value="" class="label">Dollar :</option>
								<option value="1">Dollar</option>
								<option value="2">Euro</option>
							</select>
						</div>
						<div class="box1">
							<select tabindex="4" class="dropdown">
								<option value="" class="label">English :</option>
								<option value="1">English</option>
								<option value="2">French</option>
								<option value="3">German</option>
							</select>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
				<div class="col-md-6 top-header-left">
					<div class="cart box_1">
						<a href="{% url 'main:carts' %}">
							 <div class="total">
								<span class="simpleCart_total"></span></div>
								<img src="{% static 'images/cart-1.png' %}" alt="" />
						</a>
						<p><a href="{% url 'main:carts' %}" class="simpleCart_empty">Empty Cart</a></p>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--top-header-->
		<!--start-logo-->
		<div class="logo">
			<a href="{% url 'main:index'%}"><h1>Luxury Watches</h1></a>
		</div>
		<!--start-logo-->
		<!--bottom-header-->
		<div class="header-bottom">
			<div class="container">
				<div class="header">
					<div class="col-md-9 header-left">
					<div class="top-nav">
						<ul class="memenu skyblue"><li class="active"><a href="{% url 'main:index'%}">Home</a></li>
							
							<li class="grid"><a href="#">Category</a>
								<div class="mepanel">
									<div class="row">
										<div class="col1 me-one">
											{% for i in category %}
											<a href="#"><h4>{{i.name}}</h4></a>
											{% endfor %}
										</div>
									</div>
								</div>
							</li>
							
							<li class="grid"><a href="contact.html">Contact</a>
							</li>
							<li class="grid"><a href="{% url 'account:account' %}">Login</a>
							</li>
						</ul>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="col-md-3 header-right"> 
					<div class="search-bar">
						<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
						<input type="submit" value="">
					</div>
				</div>
				<div class="clearfix"> </div>
				</div>
			</div>
		</div>
		<!--bottom-header-->

		
	<!--start-breadcrumbs-->
	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-index">
				<ol class="breadcrumb">
					<li><a href="{% url 'main:index' %}">Home</a></li>
					<li class="active">Register</li>
				</ol>
			</div>
		</div>
	</div>
	<!--end-breadcrumbs-->
{% block content %}
{% endblock %}


	<!--information-starts-->
	<div class="information">
		<div class="container">
			<div class="infor-top">
				<div class="col-md-3 infor-left">
					<h3>Follow Us</h3>
					<ul>
						<li><a href="#"><span class="fb"></span><h6>Facebook</h6></a></li>
						<li><a href="#"><span class="twit"></span><h6>Twitter</h6></a></li>
						<li><a href="#"><span class="google"></span><h6>Google+</h6></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>Information</h3>
					<ul>
						<li><a href="#"><p>Specials</p></a></li>
						<li><a href="#"><p>New Products</p></a></li>
						<li><a href="#"><p>Our Stores</p></a></li>
						<li><a href="contact.html"><p>Contact Us</p></a></li>
						<li><a href="#"><p>Top Sellers</p></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>My Account</h3>
					<ul>
						{% if user.is_authenticated %}
						<li><a href="{% url 'account:edit_profile' %}"><p>My Account</p></a></li>
						{% else %}
						<li><a href="{% url 'account:account' %}"><p>My Account</p></a></li>
						{% endif %}
						<li><a href="#"><p>My Credit slips</p></a></li>
						<li><a href="#"><p>My Merchandise returns</p></a></li>
						<li><a href="#"><p>My Personal info</p></a></li>
						<li><a href="#"><p>My Addresses</p></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>Store Information</h3>
					<h4>The company name,
						<span>Lorem ipsum dolor,</span>
						Glasglow Dr 40 Fe 72.</h4>
					<h5>+955 123 4567</h5>	
					<p><a href="mailto:example@email.com">contact@example.com</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--information-end-->
    	<!--footer-starts-->
	<div class="footer">
		<div class="container">
			<div class="footer-top">
				<div class="col-md-6 footer-left">
					<form>
						<input type="text" value="Enter Your Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email';}">
						<input type="submit" value="Subscribe">
					</form>
				</div>
				<div class="col-md-6 footer-right">					
					<p>© 2015 Luxury Watches. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--footer-end-->	
</body>
</html>

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- Product Start -->
<div class="container">
    <div class="row">
        {% for i in product %} 
                      
            <div class="col-md-3">
                <div style="display: flex; justify-content: space-between;">
                    <h2>{{product.name}}</h2>
                    {% if is_saved %}
                    <a href="{% url 'main:delete_wish' %}?id={{is_saved}}">
                        <i class="fa-solid fa-heart" style="font-size: 20px; color: crimson;" ></i>
                    </a>
                    {% else %}
                    <a href="{% url 'main:create_wishlist' %}?product_id={{i.id}}">
                        <i class="fa-regular fa-heart" style="font-size: 25px;"></i>
                    </a>
                    {% endif %}
                </div>
                <div class="product" >
                    <a href="{% url 'main:detail' i.id %}" class="mask">
                        <img class="img-responsive zoom-img" src="{{ i.baner_image.url }}" alt="{{ i.name }}" />
                    </a>
                    
                    <div class="product-info" s>
                        <h3>{{ i.name }}</h3>
                        
                        <p>{{ i.description }}</p>
                        {% if i.currency == 1 %}
                            <h4>
                                <a class="item_add" href="{% url 'main:add_to_cart' i.id %}"><i></i></a>
                                <span class="item_price">{{ i.price }} $</span>
                            </h4>
                        {% else %}
                            <h4>
                                <a class="item_add" href="{% url 'main:carts' %}"><i></i></a>
                                <span class="item_price">{{ i.price }} So'm</span>
                            </h4>
                        {% endif %}
                        <!-- Add more product details or buttons here -->
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

    <!-- Product End -->


	{% endblock %}

main/templates/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<!--start-single-->
	<div class="single contact">
		<div class="container">
			<div class="single-main">
				<div class="col-md-9 single-main-left">
				<div class="sngl-top">
					<div class="col-md-5 single-top-left">	
						<div class="flexslider">
							<ul class="slides">
								{% for image in images %}
									<li data-thumb="{{ image.image.url }}">
										<div class="thumb-image"> <img src="{{ image.image.url }}" data-imagezoom="true" class="img-responsive" alt=""/> </div>
									</li>
								{% endfor %}
							</ul>
							
							
						</div>
						<!-- FlexSlider -->
						<script src="{% static 'js/imagezoom.js' %}"></script>
						<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
						<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

						<script>
						// Can also be used with $(document).ready()
						$(window).load(function() {
						  $('.flexslider').flexslider({
							animation: "slide",
							controlNav: "thumbnails"
						  });
						});
						</script>
					</div>
				</div>
				<div class="col-md-7 single-top-right">
					<div style="display: flex; justify-content: space-between;">
                        <h2>{{product.name}}</h2>
                        {% if is_saved %}
                        <a href="{% url 'main:delete_wish' %}?id={{is_saved}}">
							<i class="fa-solid fa-heart" style="font-size: 20px; color: crimson;" ></i>
                        </a>
                        {% else %}
                        <a href="{% url 'main:create_wishlist' %}?product_id={{product.id}}">
                            <i class="fa-regular fa-heart" style="font-size: 25px;"></i>
                        </a>
                        {% endif %}
                    </div>
					<div class="single-para simpleCart_shelfItem">
					<h2>{{product.name}}</h2>
					<div class="rating-stars">
						<input type="radio" name="rating" id="rs0" checked><label for="rs0"></label>
						<input type="radio" name="rating" id="rs1"><label for="rs1"></label>
						<input type="radio" name="rating" id="rs2"><label for="rs2"></label>
						<input type="radio" name="rating" id="rs3"><label for="rs3"></label>
						<input type="radio" name="rating" id="rs4"><label for="rs4"></label>
						<input type="radio" name="rating" id="rs5"><label for="rs5"></label>
						<span class="rating-counter"></span>
					</div>	
						
						<h5 class="item_price">{{product.price}}</h5>
						<p>{{product.description}}</p>							
							<a href="{% url 'main:add_to_cart' product.id%}" class="add-cart item_add">ADD TO CART</a>
							<button type="button"  data-toggle="modal" data-target="#myModal" class="btn btn-primary">
								Baholash
							  </button>
						</div>
					</div>	
					
					<div class="clearfix"> </div>
				</div>
				<div class="tabs">
					
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
				

	<!--product-starts-->
				<div class="container">
    <div class="row">
        {% for i in recomendation %}
		{% if product.id != i.id%}
            <div class="col-md-3">
                <div class="product">
                    <a href="{% url 'main:detail' i.id %}" class="mask">
                        <img class="img-responsive zoom-img" src="{{ i.baner_image.url }}" alt="{{ i.name }}" />
                    </a>
                    <div class="product-info" s>
                        <h3>{{ i.name }}</h3>
                        <p>{{ i.description }}</p>
                        {% if i.currency == 1 %}
                            <h4>
                                <a class="item_add" href="{% url 'main:add_to_cart' i.id %}"><i></i></a>
                                <span class="item_price">{{ i.price }} $</span>
                            </h4>
                        {% else %}
                            <h4>
                                <a class="item_add" href="{% url 'main:carts' %}"><i></i></a>
                                <span class="item_price">{{ i.price }} So'm</span>
                            </h4>
                        {% endif %}
                        <!-- Add more product details or buttons here -->
                    </div>
                </div>
            </div>
			{% endif%}
        {% endfor %}
    </div>
</div>
	<!--product-end-->

	<!-- Boshlanishi Modal -->
<div class="modal fade " style="margin-bottom: auto;"     id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
	<div class="modal-dialog" role="document">
	<form method="post">
		{% csrf_token%}
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="exampleModalLabel">Baholash oynasi</h5>
		  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		  </button>
		</div>
		<div class="modal-body">
			<label >5 ballik sistemada baholang</label>
		  <input type="number" name="baho">
		</div>
		<div class="modal-footer">
		  <button type="submit" class="btn btn-primary" >Baholash</button>
		</div>
	  </div>
	  </form>
	</div>
  </div>
  <!-- Oxirishi Modal -->


	

				
						
	
				

		{% endblock %}